# Site settings
title: William.Kamovit.ch
email: wjkamovitch@gmail.com
description: "The personal blog for William Kamovitch"
baseurl: ""
url: "http://william.kamovit.ch"
twitter_username: wkamovitch
github_username:  ibexian

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
